# Generated by Django 3.2.14 on 2022-08-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0003_alter_movie_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='image',
        ),
        migrations.AddField(
            model_name='movie',
            name='img',
            field=models.ImageField(default='dfff', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
